name: Android CI - Build Debug APK

on:
  push:
    branches: [ main ]
    paths: &android_paths
      - 'android/**'
      - 'src/**'
      - 'package.json'
      - 'yarn.lock'
      - 'app.json'
      - 'index.js'
      - 'App.tsx'
      - 'babel.config.js'
      - 'tsconfig.json'
  pull_request:
    branches: [ main ]
    paths: *android_paths

jobs:
  build-android-debug:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      # Enable Corepack for Yarn
      - name: Enable Corepack and Yarn
        run: |
          corepack enable
          corepack prepare yarn@3.6.4 --activate
          yarn config set nodeLinker node-modules

      # Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Setup Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      # Setup Android
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # Gradle cache for speed
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Build Debug APK
      - name: Build Debug APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew clean assembleDebug --warning-mode all

      # Upload Artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
