name: Android CI - Build Debug APK

on:
  push:
    branches: [ main ]
    paths: &android_paths
      - 'android/**'
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'app.json'
      - 'index.js'
      - 'App.tsx'
      - 'babel.config.js'
      - 'tsconfig.json'
      - '.github/workflows/android.yml'
  pull_request:
    branches: [ main ]
    paths: *android_paths

jobs:
  build-android-debug:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      # -------------------------
      # 1️⃣ Checkout Source
      # -------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------
      # 2️⃣ Setup Node.js + Cache
      # -------------------------
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # -------------------------
      # 3️⃣ Install Dependencies
      # -------------------------
      - name: Install dependencies
        run: |
          rm -rf node_modules
          npm ci --legacy-peer-deps

      # -------------------------
      # 4️⃣ Setup Java 17
      # -------------------------
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      # -------------------------
      # 5️⃣ Setup Android SDK
      # -------------------------
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # -------------------------
      # 6️⃣ Cache Gradle
      # -------------------------
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # -------------------------
      # 7️⃣ Bundle React Native JS
      # (Fix "Unable to load script" issue)
      # -------------------------
      - name: Bundle React Native JS
        run: |
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res/

      # -------------------------
      # 8️⃣ Build Debug APK
      # -------------------------
      - name: Build Debug APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew clean assembleDebug --no-daemon --warning-mode all

      # -------------------------
      # 9️⃣ Upload Debug APK Artifact
      # -------------------------
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
