name: Build React Native iOS (Signed, Upload IPA)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    name: Build iOS Release (Signed)
    runs-on: macos-latest
    env:
      USE_HERMES: "1"
      RCT_NO_LAUNCH_PACKAGER: "true"

    steps:
      # -------------------------
      # 1️⃣ Checkout repo
      # -------------------------
      - name: 🧩 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # -------------------------
      # 2️⃣ Node & Yarn setup
      # -------------------------
      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: 🧰 Enable Corepack and Yarn 3
        run: |
          corepack enable
          corepack prepare yarn@3.6.4 --activate

      - name: 🧱 Configure Yarn Linker
        run: yarn config set nodeLinker node-modules

      # -------------------------
      # 3️⃣ Cache restore
      # -------------------------
     

      # -------------------------
      # 4️⃣ Clean & Install Dependencies
      # -------------------------
      - name: 🧹 Clean old build & caches
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData ios/build ios/Pods node_modules
          yarn cache clean

      - name: 📦 Install JS dependencies
        run: yarn install --immutable

      - name: 📦 Install iOS Pods
        run: |
          cd ios
          yarn pod-install || (pod deintegrate && pod install --repo-update)
          cd ..

      - name: 🧩 Fix Hermes scripts permissions & RN dependency analysis
        run: |
          find ios/Pods -type f -name "Script-*.sh" -exec chmod +x {} \;
          sed -i '' 's/"basedOnDependencyAnalysis" = YES;/"basedOnDependencyAnalysis" = NO;/g' ios/nvRNSDKLiveAccountTestApp.xcodeproj/project.pbxproj

      # -------------------------
      # 5️⃣ Decrypt signing assets
      # -------------------------
      - name: 🔐 Decrypt signing assets
        env:
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
        run: |
          set -e
          mkdir -p ios/certs
          openssl aes-256-cbc -k "$CERT_PASSWORD" -in pf_ios/appleDistribution.p12.enc -out ios/certs/appleDistribution.p12 -d
          openssl aes-256-cbc -k "$CERT_PASSWORD" -in pf_ios/main_Target.mobileprovision.enc -out ios/certs/ad_hoc_main_Target.mobileprovision -d
          openssl aes-256-cbc -k "$CERT_PASSWORD" -in pf_ios/ext_Target.mobileprovision.enc -out ios/certs/ad_hoc_ext_Target.mobileprovision -d

      # -------------------------
      # 6️⃣ Keychain & certificate
      # -------------------------
      - name: 🔑 Create keychain and import certificate
        env:
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
        run: |
          set -e
          KEYCHAIN_NAME=build.keychain
          security create-keychain -p "" "$KEYCHAIN_NAME"
          security import ios/certs/appleDistribution.p12 -k ~/Library/Keychains/$KEYCHAIN_NAME -P "$CERT_PASSWORD" -T /usr/bin/codesign
          security list-keychains -s ~/Library/Keychains/$KEYCHAIN_NAME
          security default-keychain -s ~/Library/Keychains/$KEYCHAIN_NAME
          security unlock-keychain -p "" ~/Library/Keychains/$KEYCHAIN_NAME
          security set-key-partition-list -S apple-tool:,apple: -s -k "" ~/Library/Keychains/$KEYCHAIN_NAME

      # -------------------------
      # 7️⃣ Install Provisioning Profiles
      # -------------------------
      - name: 📄 Install Provisioning Profiles
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp ios/certs/ad_hoc_main_Target.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          cp ios/certs/ad_hoc_ext_Target.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      # -------------------------
      # 8️⃣ Bundle React Native JS
      # -------------------------
      - name: 📦 Bundle React Native JS
        run: |
          npx react-native bundle \
            --entry-file index.js \
            --platform ios \
            --dev false \
            --bundle-output ios/main.jsbundle \
            --assets-dest ios

      # -------------------------
      # 9️⃣ Install xcpretty
      # -------------------------
      - name: 💎 Install xcpretty
        run: gem install xcpretty

      # -------------------------
      # 🔟 Build & Archive iOS App
      # -------------------------
      - name: 🏗️ Build & Archive iOS App (Signed)
        env:
          APP_SCHEME: nvRNSDKLiveAccountTestApp
          WORKSPACE: nvRNSDKLiveAccountTestApp.xcworkspace
          CONFIGURATION: Release
          DEVELOPMENT_TEAM: 4JW4924F8P
          PROFILE_APP_NAME: "nvRNLiveAcTestApp Main Target Dist AppStoreProfile"
          PROFILE_EXT_NAME: "nvRNLiveAcTestApp Ser Ext Target Dist AppStoreProf"
        run: |
          set -e
          cd ios
          mkdir -p build

          # Fix dependency analysis
          find . -name "project.pbxproj" -exec sed -i '' 's/"basedOnDependencyAnalysis" = YES;/"basedOnDependencyAnalysis" = NO;/g' {} \; || true

          # ExportOptions.plist
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>ad-hoc</string>
            <key>teamID</key>
            <string>${DEVELOPMENT_TEAM}</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>compileBitcode</key>
            <false/>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>destination</key>
            <string>export</string>
            <key>thinning</key>
            <string>&lt;none&gt;</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.notifyvisitors.rn.nvrnsdkliveaccounttestapp</key>
              <string>${PROFILE_APP_NAME}</string>
              <key>com.notifyvisitors.rn.nvrnsdkliveaccounttestapp.NVRNPushServiceExt</key>
              <string>${PROFILE_EXT_NAME}</string>
            </dict>
          </dict>
          </plist>
          EOF

          # Clean previous builds
          xcodebuild clean -workspace "$WORKSPACE" -scheme "$APP_SCHEME" -configuration "$CONFIGURATION"

          # Archive
          ARCHIVE_PATH="$PWD/build/${APP_SCHEME}.xcarchive"
          set -o pipefail
          xcodebuild -workspace "$WORKSPACE" \
            -scheme "$APP_SCHEME" \
            -configuration "$CONFIGURATION" \
            -sdk iphoneos \
            -archivePath "$ARCHIVE_PATH" \
            DEVELOPMENT_TEAM="${DEVELOPMENT_TEAM}" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="iPhone Distribution" \
            archive | tee xcodebuild.log | xcpretty || (cat xcodebuild.log && exit 1)

          # Export signed IPA
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportPath "$PWD/build" \
            -exportOptionsPlist ExportOptions.plist | xcpretty

          echo "IPA files:"
          ls -la build/*.ipa || true
          cd ..

      # -------------------------
      # 1️⃣1️⃣ Upload IPA Artifact
      # -------------------------
      - name: ☁️ Upload iOS IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-ios
          path: ios/build/*.ipa
